# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=200, overwrite=True, populate_from='name', unique=True)),
                ('about', models.TextField(blank=True, max_length=10000, verbose_name='About')),
            ],
        ),
    ]
