# Generated by Django 2.2.7 on 2019-11-20 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en-us', 'English'), ('pt-br', 'Portuguese')], max_length=50, null=True, verbose_name='Language')),
                ('about_me', models.TextField(blank=True, max_length=500, null=True, verbose_name='About me')),
                ('github', models.CharField(blank=True, max_length=50, null=True, verbose_name='Github username')),
                ('facebook', models.CharField(blank=True, max_length=50, null=True, verbose_name='Facebook username')),
                ('twitter', models.CharField(blank=True, max_length=50, null=True, verbose_name='Twitter username')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Site url')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
    ]
