# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170823_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='About me'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Facebook username'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Github username'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='site',
            field=models.URLField(blank=True, null=True, verbose_name='Site url'),
        ),
    ]
