# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[(b'en-us', b'English'), (b'pt-br', 'Portugu\xeas')], max_length=50, null=True, verbose_name='Language'),
        ),
    ]
