# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 00:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_language'),
        ('core', '0004_profile_language'),
    ]

    operations = [
    ]
