# Generated by Django 2.2.7 on 2019-11-20 03:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(related_name='juries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jury',
                'verbose_name_plural': 'Juries',
            },
        ),
    ]
