# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0003_auto_20150728_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jury',
            options={'verbose_name': 'Juri', 'verbose_name_plural': 'j\xfaris'},
        ),
    ]
