# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0004_auto_20170823_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jury',
            options={'verbose_name': 'Jury', 'verbose_name_plural': 'Juries'},
        ),
    ]
