# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0014_event_anonymous_voting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('track_order', 'start_timetable', 'pk'), 'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividades'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-due_date', '-created_at'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ['title'], 'verbose_name': 'Proposta', 'verbose_name_plural': 'Propostas'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'verbose_name': 'Trilha', 'verbose_name_plural': 'Trilhas'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Voto', 'verbose_name_plural': 'Votos'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[(b'proposal', 'Proposta'), (b'workshop', 'Minicurso'), (b'openning', 'Abertura'), (b'coffee-break', 'Pausa para caf\xe9'), (b'lunch', 'Almo\xe7o'), (b'lightning-talks', 'Palestras Rel\xe2mpago'), (b'ending', 'Encerramento')], default=b'proposal', max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Descri\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_timetable',
            field=models.TimeField(null=True, verbose_name='Hora de Fim'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Publicar'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_timetable',
            field=models.TimeField(null=True, verbose_name='Hora de In\xedcio'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=200, verbose_name='T\xedtulo'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='track_order',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='event',
            name='allow_public_voting',
            field=models.BooleanField(default=True, verbose_name='Permitir vota\xe7\xe3o p\xfablica'),
        ),
        migrations.AlterField(
            model_name='event',
            name='anonymous_voting',
            field=models.BooleanField(default=False, verbose_name='Vota\xe7\xe3o An\xf4nima?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Descri\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Publicar'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slots',
            field=models.SmallIntegerField(default=10, verbose_name='Vagas'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='T\xedtulo'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Aprovada'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='more_information',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Mais informa\xe7\xf5es'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=200, verbose_name='T\xedtulo'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='rate',
            field=models.SmallIntegerField(blank=True, choices=[(-1, b'angry'), (1, b'sad'), (0, b'sleepy'), (2, b'happy'), (3, b'laughing')], null=True, verbose_name='\xcdndice de classfica\xe7\xe3o'),
        ),
    ]
