# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0015_auto_20170823_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('track_order', 'start_timetable', 'pk'), 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-due_date', '-created_at'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ['title'], 'verbose_name': 'Proposal', 'verbose_name_plural': 'Proposals'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'verbose_name': 'Track', 'verbose_name_plural': 'Tracks'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Vote', 'verbose_name_plural': 'Votes'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[(b'proposal', 'Proposal'), (b'workshop', 'Workshop'), (b'openning', 'Openning'), (b'coffee-break', 'Coffee Break'), (b'lunch', 'Lunch'), (b'lightning-talks', 'Lightning Talks'), (b'ending', 'Ending')], default=b'proposal', max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_timetable',
            field=models.TimeField(null=True, verbose_name='End Timetable'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Publish'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_timetable',
            field=models.TimeField(null=True, verbose_name='Start Timetable'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='track_order',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='event',
            name='allow_public_voting',
            field=models.BooleanField(default=True, verbose_name='Allow Public Voting'),
        ),
        migrations.AlterField(
            model_name='event',
            name='anonymous_voting',
            field=models.BooleanField(default=False, verbose_name='Anonymous Voting?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Publish'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slots',
            field=models.SmallIntegerField(default=10, verbose_name='Slots'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Is approved'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='more_information',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='More information'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='rate',
            field=models.SmallIntegerField(blank=True, choices=[(-1, b'angry'), (1, b'sad'), (0, b'sleepy'), (2, b'happy'), (3, b'laughing')], null=True, verbose_name='Rate Index'),
        ),
    ]
