# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 20:04
from __future__ import unicode_literals

from django.db import migrations, models


def copy_created_at_to_due_date(apps, schema_editor):
    Event = apps.get_model('deck', 'Event')
    Event.objects.filter(due_date__isnull=True).update(
        due_date=models.F('created_at')
    )


def undo_created_at_to_due_date(apps, schema_editor):
    Event = apps.get_model('deck', 'Event')
    Event.objects.filter(due_date=models.F('created_at')).update(due_date=None)


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0016_auto_20170824_1446'),
    ]

    operations = [
        migrations.RunPython(
            copy_created_at_to_due_date, 
            undo_created_at_to_due_date),
        migrations.AlterField(
            model_name='event',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
