# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0017_auto_20170922_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-closing_date', '-created_at'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='due_date',
            new_name='closing_date',
        ),
    ]
