# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0017_auto_20170922_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='paper_closing_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
