# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0017_auto_20170922_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='slides_url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='speakerdeck.com'),
        ),
    ]
