# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0018_event_paper_closing_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='paper_closing_date',
            new_name='event_date',
        ),
    ]
