# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0018_proposal_slides_url'),
        ('deck', '0018_auto_20171011_1213'),
    ]

    operations = [
    ]
